// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeOptimizer.Infrastructure.Data;

#nullable disable

namespace RecipeOptimizer.Infrastructure.Migrations
{
    [DbContext(typeof(RecipeOptimizerDbContext))]
    partial class RecipeOptimizerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeOptimizer.Core.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 6,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 3,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 6,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 8,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 10,
                            Name = "Dough"
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 2,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 2,
                            Name = "Olives"
                        });
                });

            modelBuilder.Entity("RecipeOptimizer.Core.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ServingSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Burger",
                            ServingSize = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pie",
                            ServingSize = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sandwich",
                            ServingSize = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pasta",
                            ServingSize = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Salad",
                            ServingSize = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pizza",
                            ServingSize = 4
                        });
                });

            modelBuilder.Entity("RecipeOptimizer.Core.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            RecipeId = 1,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            RecipeId = 1,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            RecipeId = 1,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 4,
                            RecipeId = 1,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 5,
                            RecipeId = 1,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 1,
                            RecipeId = 2,
                            RequiredQuantity = 2
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 5,
                            RecipeId = 2,
                            RequiredQuantity = 2
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 5,
                            RecipeId = 3,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 9,
                            IngredientId = 6,
                            RecipeId = 3,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 1,
                            RecipeId = 4,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 11,
                            IngredientId = 3,
                            RecipeId = 4,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 12,
                            IngredientId = 4,
                            RecipeId = 4,
                            RequiredQuantity = 2
                        },
                        new
                        {
                            Id = 13,
                            IngredientId = 5,
                            RecipeId = 4,
                            RequiredQuantity = 2
                        },
                        new
                        {
                            Id = 14,
                            IngredientId = 6,
                            RecipeId = 5,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 15,
                            IngredientId = 2,
                            RecipeId = 5,
                            RequiredQuantity = 2
                        },
                        new
                        {
                            Id = 16,
                            IngredientId = 3,
                            RecipeId = 5,
                            RequiredQuantity = 2
                        },
                        new
                        {
                            Id = 17,
                            IngredientId = 4,
                            RecipeId = 5,
                            RequiredQuantity = 2
                        },
                        new
                        {
                            Id = 18,
                            IngredientId = 7,
                            RecipeId = 5,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 19,
                            IngredientId = 7,
                            RecipeId = 6,
                            RequiredQuantity = 1
                        },
                        new
                        {
                            Id = 20,
                            IngredientId = 3,
                            RecipeId = 6,
                            RequiredQuantity = 2
                        },
                        new
                        {
                            Id = 21,
                            IngredientId = 4,
                            RecipeId = 6,
                            RequiredQuantity = 3
                        },
                        new
                        {
                            Id = 22,
                            IngredientId = 5,
                            RecipeId = 6,
                            RequiredQuantity = 3
                        });
                });

            modelBuilder.Entity("RecipeOptimizer.Core.Models.RecipeIngredient", b =>
                {
                    b.HasOne("RecipeOptimizer.Core.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeOptimizer.Core.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeOptimizer.Core.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
