name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Build and test
      run: |
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
    
    - name: Publish .NET application
      run: |
        dotnet publish RecipeOptimizer.API/RecipeOptimizer.API.csproj -c Release -o ./publish
    
    - name: Create deployment package
      run: |
        # Create .ebextensions directory for environment configuration
        mkdir -p .ebextensions
        
        # Create RDS environment configuration
        cat > .ebextensions/01-environment.config << EOF
        option_settings:
          aws:elasticbeanstalk:application:environment:
            ASPNETCORE_ENVIRONMENT: Production
        EOF
        
        cat > .ebextensions/02-rds-environment.config << EOF
        option_settings:
          aws:elasticbeanstalk:application:environment:
            RDS_HOSTNAME: \${RDS_HOSTNAME}
            RDS_PORT: \${RDS_PORT}
            RDS_DB_NAME: \${RDS_DB_NAME}
            RDS_USERNAME: \${RDS_USERNAME}
            RDS_PASSWORD: \${RDS_PASSWORD}
        EOF
        
        # Create Procfile for application startup
        echo "web: cd /app && dotnet RecipeOptimizer.API.dll --urls=http://+:80" > Procfile
        
        # Copy configuration files to publish directory
        cp Dockerrun.aws.json ./publish/
        cp -r .ebextensions ./publish/
        cp Procfile ./publish/
        
        # Create deployment package
        cd publish
        zip -r ../deploy.zip *
        cd ..
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: recipe-optimizer
        environment_name: recipe-optimizer-prod
        version_label: ${{ github.sha }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: deploy.zip
        wait_for_deployment: true
        use_existing_version_if_available: false
